---
name: WAU - Create New Version

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        default: "Patch"
        description: Select next release type
        options:
          - Patch
          - Minor
          - Major
        required: true
      pre-release:
        type: boolean
        description: Set as Pre-release version

permissions:
  contents: write

jobs:
  build:
    name: Create Release Asset
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: "true"

      - name: Auto Increment Semver Action
        uses: MCKanpolat/auto-semver-action@5003b8d37f4b03d95f15303ea10242cbf7c13141 # 1.0.11
        id: versioning
        with:
          releaseType: ${{ github.event.inputs.version }}
          incrementPerCommit: false
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Next Release Number
        id: WAU_version
        run: |
          echo "Next Release version: ${{ steps.versioning.outputs.version }}"

      - name: Build project
        shell: powershell
        run: |
          echo "### Get MDT from Microsoft ###"
          wget https://download.microsoft.com/download/3/3/9/339BE62D-B4B8-4956-B58D-73C4685FC492/MicrosoftDeploymentToolkit_x64.msi -UseBasicParsing -OutFile .\MicrosoftDeploymentToolkit_x64.msi
          Start-Process .\MicrosoftDeploymentToolkit_x64.msi -ArgumentList "/quiet /norestart" -Wait

          echo "### Duplicate WAU to WAU_x86 and WAU_x64"
          Copy-Item -Path ".\Sources\Winget-AutoUpdate" -Destination ".\Sources\Winget-AutoUpdate_x64" -Recurse -Force
          #Copy-Item -Path ".\Sources\Winget-AutoUpdate" -Destination ".\Sources\Winget-AutoUpdate_x86" -Recurse -Force

          echo "### Copy ServiceUI.exe (x64/x86) to 'Sources/WAU_(x86/x64)/Winget-AutoUpdate' folders ###"
          Copy-Item -Path "C:\Program Files\Microsoft Deployment Toolkit\Templates\Distribution\Tools\x64\ServiceUI.exe" -Destination ".\Sources\Winget-AutoUpdate_x64\ServiceUI.exe" -Force
          #Copy-Item -Path "C:\Program Files\Microsoft Deployment Toolkit\Templates\Distribution\Tools\x86\ServiceUI.exe" -Destination ".\Sources\Winget-AutoUpdate_x86\ServiceUI.exe" -Force

          echo "### Create WAU msi ###"
          .\Sources\Wix\Make_MSI.ps1 -Sources ".\Sources\Winget-AutoUpdate_x64" -OutputFolder ".\" -ProductVersion ${{ steps.versioning.outputs.version }} -NoX86
          #.\Sources\Wix\Make_MSI.ps1 -Sources ".\Sources\Winget-AutoUpdate_x86" -OutputFolder ".\" -ProductVersion ${{ steps.versioning.outputs.version }} -NoX64

          echo "### Get file SHA ###"
          $MsiSHA = (Get-FileHash .\WAU.msi).hash
          echo " - WAU.msi SHA256: $MsiSHA"
          echo "MSI_SHA=$MsiSHA" >> $env:GITHUB_ENV
          #$MsiX86HA = (Get-FileHash .\WAU_x86.msi).hash
          #echo " - WAU_x86.msi SHA256: $MsiX86HA"
          #echo "MSI_SHA_X86=$MsiX86HA" >> $env:GITHUB_ENV

          echo "### Zip ADMX ###"
          Compress-Archive -Path .\Sources\Policies\ADMX -DestinationPath .\WAU_ADMX.zip -Force

          echo "### Create install counter file ###"
          echo "Install counter file." > WAU_InstallCounter

      - name: Create release
        uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5 # v1.14.0
        id: release
        with:
          tag: "v${{ steps.versioning.outputs.version }}"
          prerelease: ${{ github.event.inputs.pre-release }}
          generateReleaseNotes: true
          name: "v${{ steps.versioning.outputs.version }}"
          artifacts: "WAU.msi,WAU_ADMX.zip,WAU_InstallCounter"
          body: "WAU.msi SHA256: ${{ env.MSI_SHA }}"

      - name: URL to release
        run: echo "Release -> ${{ steps.release.outputs.html_url }}"
