---
name: WAU - Create New Version

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        default: "Patch"
        description: Select next release type
        options:
          - Patch
          - Minor
          - Major
        required: true
      pre-release:
        type: boolean
        description: Set as Pre-release version

permissions:
  contents: write

jobs:
  build:
    name: Create Release Asset
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: "true"

      - name: Auto Increment Semver Action
        uses: MCKanpolat/auto-semver-action@5003b8d37f4b03d95f15303ea10242cbf7c13141 # 2
        id: versioning
        with:
          releaseType: ${{ github.event.inputs.version }}
          incrementPerCommit: false
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Overwrite Version.txt file
        uses: DamianReeves/write-file-action@6929a9a6d1807689191dcc8bbe62b54d70a32b42 # v1.3
        with:
          path: Sources/WAU/Winget-AutoUpdate/Version.txt
          write-mode: overwrite
          contents: "${{ steps.versioning.outputs.version }}"

      - name: Commit & Push
        uses: actions-js/push@156f2b10c3aa000c44dbe75ea7018f32ae999772 # v1.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          message: "Changed version to ${{ steps.versioning.outputs.version }}"

      - name: Build project
        shell: powershell
        run: |
          echo "### Get MDT from Microsoft ###"
          wget https://download.microsoft.com/download/3/3/9/339BE62D-B4B8-4956-B58D-73C4685FC492/MicrosoftDeploymentToolkit_x64.msi

          echo "### Install MSI ###"
          Start-Process msiexec.exe -ArgumentList "/i MicrosoftDeploymentToolkit_x64.msi /qn /norestart" -Wait

          echo "### Copy ServiceUI.exe to 'Sources/WAU/Winget-AutoUpdate' folder ###"
          Copy-Item -Path "$env:ProgramFiles\Microsoft Deployment Toolkit\Templates\Distribution\Tools\x64\ServiceUI.exe" -Destination ./Sources/WAU/Winget-AutoUpdate/ServiceUI.exe -Force

          echo "### Go to Sources ###"
          cd .\Sources

          echo "### Create WAU msi ###"
          cd .\Wix
          .\Make_MSI.ps1 -ProductVersion ${{ steps.versioning.outputs.version }} $OutputFolder ..\..\
          cd ..

          echo "### Zip ADMX ###"
          cd Policies
          Compress-Archive -Path .\ADMX -DestinationPath ..\..\WAU_ADMX.zip -Force
          cd ../..

          echo "### Create install counter file ###"
          echo "Install counter file." > WAU_InstallCounter

      - name: Create release
        uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5 # v1.14.0
        id: release
        with:
          tag: "v${{ steps.versioning.outputs.version }}"
          prerelease: true
          generateReleaseNotes: true
          name: "v${{ steps.versioning.outputs.version }} [Nightly Build]"
          artifacts: "WAU_x86.zip,WAU_x64.msi,WAU_ADMX.zip,WAU_InstallCounter"