---
name: WAU - Create New Version

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        default: "Patch"
        description: Select next release type
        options:
          - Patch
          - Minor
          - Major
        required: true
      pre-release:
        type: boolean
        description: Set as Pre-release version

permissions:
  contents: write

jobs:
  build:
    name: Create Release Asset
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: "true"

      - name: Auto Increment Semver Action
        uses: MCKanpolat/auto-semver-action@5003b8d37f4b03d95f15303ea10242cbf7c13141 # 1.0.11
        id: versioning
        with:
          releaseType: ${{ github.event.inputs.version }}
          incrementPerCommit: false
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Next Release Number
        id: WAU_version
        run: |
          echo "Next Release version: ${{ steps.versioning.outputs.version }}"

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build project
        shell: powershell
        run: |
          echo "### Get MDT from Microsoft ###"
          wget https://download.microsoft.com/download/3/3/9/339BE62D-B4B8-4956-B58D-73C4685FC492/MicrosoftDeploymentToolkit_x64.msi -UseBasicParsing -OutFile .\MicrosoftDeploymentToolkit_x64.msi
          Start-Process .\MicrosoftDeploymentToolkit_x64.msi -ArgumentList "/quiet /norestart" -Wait

          echo "### Copy ServiceUI.exe x64 to 'Sources\Winget-AutoUpdate' folder ###"
          Copy-Item -Path "C:\Program Files\Microsoft Deployment Toolkit\Templates\Distribution\Tools\x64\ServiceUI.exe" -Destination ".\Sources\Winget-AutoUpdate\ServiceUI.exe" -Force
          Get-Item .\Sources\Winget-AutoUpdate\*

          echo "### Install WiX"
          dotnet new console
          dotnet tool install --global wix --version 5.0.1
          wix extension add WixToolset.UI.wixext/5.0.1 -g
          wix extension add WixToolset.Util.wixext/5.0.1 -g

          echo "### Create WAU msi ###"
          cd .\Sources\Wix\
          wix build -src build.wxs -ext WixToolset.Util.wixext -ext WixToolset.UI.wixext -out ..\..\WAU.msi -arch x64 -d Version=${{ steps.versioning.outputs.version }} -d Comment=STABLE -d PreRelease=0
          cd ..\..
          Get-Item .\WAU.msi

          echo "### Get MSI file SHA ###"
          $MsiSHA = (Get-FileHash .\WAU.msi).hash
          echo " - WAU.msi SHA256: $MsiSHA"
          echo "MSI_SHA=$MsiSHA" >> $env:GITHUB_ENV

          echo "### Zip ADMX ###"
          Compress-Archive -Path .\Sources\Policies\ADMX -DestinationPath .\WAU_ADMX.zip -Force
          Get-Item .\*.zip

          echo "### Get ADMX zip SHA ###"
          $ADMXSHA = (Get-FileHash .\WAU_ADMX.zip).hash
          echo " - WAU_ADMX.zip SHA256: $ADMXSHA"
          echo "ADMX_SHA=$ADMXSHA" >> $env:GITHUB_ENV

          echo "### Create install counter file ###"
          echo "Install counter file." > WAU_InstallCounter

      - name: Create release
        uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5 # v1.14.0
        id: release
        with:
          tag: "v${{ steps.versioning.outputs.version }}"
          prerelease: ${{ github.event.inputs.pre-release }}
          generateReleaseNotes: true
          name: "v${{ steps.versioning.outputs.version }}"
          artifacts: "WAU.msi,WAU_ADMX.zip,WAU_InstallCounter"
          body: |
            |Files|Hash (SHA256)|Downloads|
            |---|---|---|
            |[WAU.msi](https://github.com/Romanitho/WAU-MSI/releases/download/v${{ steps.versioning.outputs.version }}/WAU.msi) (x64)|${{ env.MSI_SHA }}|<picture>![WAU](https://img.shields.io/github/downloads/Romanitho/WAU-MSI/v${{ steps.versioning.outputs.version }}/WAU.msi?style=flat-square&label=&color=blue)</picture>|
            |[WAU_ADMX.zip](https://github.com/Romanitho/WAU-MSI/releases/download/v${{ steps.versioning.outputs.version }}/WAU_ADMX.zip)|${{ env.ADMX_SHA }}|<picture>![WAU_ADMX](https://img.shields.io/github/downloads/Romanitho/WAU-MSI/v${{ steps.versioning.outputs.version }}/WAU_ADMX.zip?style=flat-square&label=&color=blue)</picture>|

            <picture>![Install counter](https://img.shields.io/github/downloads/Romanitho/WAU-MSI/v${{ steps.versioning.outputs.version }}/WAU_InstallCounter?style=flat-square&label=Total%20reported%20installations%20for%20this%20release&color=blue)</picture>

      - name: URL to release
        run: echo "Release -> ${{ steps.release.outputs.html_url }}"
